<?php

/**
 * Test class for WSRequestParameters.
 * Generated by PHPUnit on 2012-06-13 at 09:47:17.
 * @group WebServices
 */
class WSRequestParametersTest extends PHPUnit\Framework\TestCase {

    /**
     * @var WSRequestParameters
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() :void {
        $this->object = new WSRequestParameters;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() :void {
        
    }

}

